name: "Setup environment"
description: "This action install node, pnpm & Go toolchain"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6.3.0
      with:
        node-version: lts/*

    - uses: pnpm/action-setup@v5.0.0
      with:
        run_install: true
    - uses: actions/setup-go@v5
      with:
        go-version: 1.25.1
