name: CI
on:
  pull_request:

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

env:
  CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v6.0.2
       - uses: ./.github/actions/setup
       - run: make build-ci
  lint_and_format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v6.0.2
       - uses: ./.github/actions/setup
         with:
           setup-go: "true"
       - name: golangci-lint
         uses: golangci/golangci-lint-action@v9.2.0
         with:
           version: v2.11.3
           install-only: true
       - run: make lint-ci
       - run: make format
       - name: Check dirty files
         id: check-dirty
         run: git diff --no-ext-diff --exit-code
       - name: Dirty files message
         if: failure() && steps.check-dirty.outcome == 'failure'
         run: echo "::error::Uncommitted changes detected. Run 'make format' locally."
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v6.0.2
       - uses: ./.github/actions/setup
         with:
           setup-go: "true"
       - run: make test-ci
  subgraphs-check:
    name: Check GraphQL schemas
    runs-on: ubuntu-latest
    env:
      COSMO_API_KEY: ${{ secrets.COSMO_API_KEY }}
    steps:
       - uses: actions/checkout@v6.0.2
       - uses: ./.github/actions/setup
       - run: make check-subgraphs
