name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'wundergraph/cosmo-onboarding' }}
    env:
      COSMO_API_KEY: ${{ secrets.COSMO_API_KEY }}
    steps:
     - uses: actions/checkout@v6.0.2
     - uses: ./.github/actions/setup
     - run: make check-subgraphs
     - run: make publish-ci

  # Internal deployment specific to WunderGraph
  deploy-wundergraph:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'wundergraph/cosmo-onboarding' }}
    env:
      COSMO_API_KEY: ${{ secrets.COSMO_API_KEY }}
      REVIEWS_SUBGRAPH_NAME: ${{ vars.REVIEWS_SUBGRAPH_NAME }}
      PRODUCTS_SUBGRAPH_NAME: ${{ vars.PRODUCTS_SUBGRAPH_NAME }}
    steps:
     - uses: actions/checkout@v6.0.2
     - uses: ./.github/actions/setup
     - run: make check-subgraphs
     - run: make publish-ci
